name: gems
description: Green Environment Maintenance System — Abiola Ajimobi Technical University

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Backend
  supabase_flutter: 2.3.4

  # UI & animations
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
